// ! Element types
//?objects
//tools
//elements
//background cells do not interact

//! State
//?Update
//TODO click on sidebar button focuses
//click on focused button - unfocuses
//active tool
//current inventory
//is inventory active

//surrounding blocks of inventory so can't put block in the air for exp

//! Layout
//?main
//start menu
//background pixel white image
//? grid
/// 20x20 vmin
/// grid cell = background blue

/// e.target for click turns background blue + adds target to inventory
//?aside
//toolbar
//buttons

//! Draw()
//draw starting world
//use 2d array matrix with rows and type of block for each cell

//! Physics
//surrounding blocks of inventory so can't put block in the air for exp
